language: ruby
rvm:
  - 1.9.3
  - 2.0.0-preview1
before_install:
  - rvm get stable
  - rvm install ruby-2.0.0-preview1
  - rvm reload
  - gem install bundler
before_script:
  - sudo apt-get update
  - sudo apt-get install pdftk
  - sudo updatedb -U /usr/bin
script:
  - bundle exec rake test
notifications:
  email:
    - joneslee85@gmail.com
matrix:
  allow_failures:
    - rvm: 2.0.0-preview1
